### ISSUE TITLE
Exception: Could not find main GSSAPI shared library.

### ISSUE THREAD

**Issue by chopraaa** [jborean93/pypsexec#3]
Running into this exception trying to install `pypsexec`. 

```
$ pip install pypsexec
Collecting pypsexec
  Using cached pypsexec-0.0.1.dev0-py2.py3-none-any.whl
Collecting smbprotocol==0.0.1.dev0 (from pypsexec)
  Using cached smbprotocol-0.0.1.dev0-py2.py3-none-any.whl
Requirement already satisfied: six in /usr/lib/python2.7/site-packages (from smbprotocol==0.0.1.dev0->pypsexec)
Requirement already satisfied: cryptography>=2.0 in /usr/lib64/python2.7/site-packages (from smbprotocol==0.0.1.dev0->pypsexec)
Requirement already satisfied: ntlm-auth in /usr/lib/python2.7/site-packages (from smbprotocol==0.0.1.dev0->pypsexec)
Requirement already satisfied: pyasn1 in /usr/lib/python2.7/site-packages (from smbprotocol==0.0.1.dev0->pypsexec)
Collecting gssapi>=1.4.1; sys_platform != "win32" (from smbprotocol==0.0.1.dev0->pypsexec)
  Using cached gssapi-1.4.1.tar.gz
    Complete output from command python setup.py egg_info:
    In distributed package, building from C files...
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-SzARoM/gssapi/setup.py", line 98, in <module>
        raise Exception("Could not find main GSSAPI shared library.  Please "
    Exception: Could not find main GSSAPI shared library.  Please try setting GSSAPI_MAIN_LIB yourself or setting ENABLE_SUPPORT_DETECTION to 'false'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-SzARoM/gssapi/
```

I'm running RHEL 7.4.

**Comment by jborean93** [comment]
@chopraaa looks like python-gssapi requires the main krb5 libraries (makes sense). I should probably set it to be an optional dependency for smbprotocol so you can install it without it.

**Comment by jborean93** [comment]
Thansk @chopraaa, the 0.0.1.dev1 release fixes this issue and makes kerberos auth an optional dependency, now running `pip install pypsexec` will not require gssapi. If you do still want Kerb auth
support you can manually run `pip install smbprotocol[kerberos]`

https://pypi.python.org/pypi/smbprotocol/0.0.1.dev1
https://pypi.python.org/pypi/pypsexec/0.0.1.dev1
