### ISSUE TITLE
smbprotocol.exceptions.SMBException: Connection timeout of 10 seconds exceeded while waiting for a message id 0 response from the server

### ISSUE THREAD

**Issue by freedom-wy** [jborean93/pypsexec#34]
When I use cmd to access windows share
`
```
C:\Users\win7user1>dir \\dtest.dc.test.com\c$
 驱动器 \\dtest.dc.test.com\c$ 中的卷没有标签。
 卷的序列号是 74B2-FB47

 \\dtest.dc.test.com\c$ 的目录

2020/11/18  14:50                 0 AUTOEXEC.BAT
2020/11/18  14:50                 0 CONFIG.SYS
2020/11/18  14:52    <DIR>          Documents and Settings
2020/11/18  14:54    <DIR>          Program Files
2020/11/25  18:04    <DIR>          WINDOWS
2020/11/18  14:50    <DIR>          wmpub
               2 个文件              0 字节
               4 个目录 38,371,938,304 可用字节
```
`

but i use pypsexec
`
```
from pypsexec.client import Client
server = "dtest.dc.test.com"
c = Client(server, port=445)
c.connect(timeout=10)
```
`
result
`
```
Traceback (most recent call last):
  File "C:/tools/intranet_hack_tools/test.py", line 35, in <module>
    c.connect(timeout=10)
  File "C:\Users\win7user1\AppData\Roaming\Python\Python37\site-packages\pypsexec\client.py", line 60, in connect
    self.connection.connect(timeout=timeout)
  File "C:\Users\win7user1\AppData\Roaming\Python\Python37\site-packages\smbprotocol\connection.py", line 735, in connect
    smb_response = self._send_smb2_negotiate(dialect, timeout)
  File "C:\Users\win7user1\AppData\Roaming\Python\Python37\site-packages\smbprotocol\connection.py", line 1336, in _send_smb2_negotiate
    response = self.receive(request, timeout=timeout)
  File "C:\Users\win7user1\AppData\Roaming\Python\Python37\site-packages\smbprotocol\connection.py", line 617, in wrapped
    return func(self, *args, **kwargs)
  File "C:\Users\win7user1\AppData\Roaming\Python\Python37\site-packages\smbprotocol\connection.py", line 855, in receive
    "response from the server" % (timeout, request.message['message_id'].get_value()))
smbprotocol.exceptions.SMBException: Connection timeout of 10 seconds exceeded while waiting for a message id 0 response from the server
```
`

why?

**Comment by jborean93** [comment]
Based on your dir output it looks like you are trying to connect to a really old Windows version like Server 2003. You need to have Server 2008 or newer because this only support SMB 2 or newer. There’s nothing that can be done to change as as I will not be implementing SMB 1 ever.

**Comment by freedom-wy** [comment]
@jborean93 thank you。
