### ISSUE TITLE
TimeoutError: [Errno 60] Operation timed out on macOS

### ISSUE THREAD

**Issue by hdansou** [jborean93/pypsexec#5]
When testing `pypsexec` on macOS 10.13.3  and 10.11, I got the following errors on python 3 and python2. I don't think I have a connection issue with the destination server over the port 445 because I can access it from a Windows computer, using psexec.

## Error from python2 test

```
2018-03-02 14:33:36,196 - pypsexec.client - INFO - Creating PyPsexec Client with unique name: PAExec-82534-ComputerName
2018-03-02 14:33:36,196 - pypsexec.client - INFO - Generated unique ID for PyPsexec Client: 5587499
2018-03-02 14:33:36,196 - pypsexec.client - INFO - Setting up SMB Connection to 1.1.1.1:445
Traceback (most recent call last):
  File "/Users/username/Test-PyPsExec.py", line 24, in <module>
    c.connect()
  File "/usr/local/lib/python2.7/site-packages/pypsexec/client.py", line 59, in connect
    self.connection.connect(timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/smbprotocol/connection.py", line 835, in connect
    self.transport.connect()
  File "/usr/local/lib/python2.7/site-packages/smbprotocol/transport.py", line 60, in connect
    self._sock.connect((self.server, self.port))
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 60] Operation timed out
```

##  Error from python3 test

```
2018-03-02 14:28:52,060 - pypsexec.client - INFO - Creating PyPsexec Client with unique name: PAExec-82417-ComputerName
2018-03-02 14:28:52,067 - pypsexec.client - INFO - Generated unique ID for PyPsexec Client: 5587388
2018-03-02 14:28:52,067 - pypsexec.client - INFO - Setting up SMB Connection to 1.1.1.1:445
Traceback (most recent call last):
  File "/Users/username/Test-PyPsExec.py", line 24, in <module>
    c.connect()
  File "/usr/local/lib/python3.6/site-packages/pypsexec/client.py", line 59, in connect
    self.connection.connect(timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/smbprotocol/connection.py", line 835, in connect
    self.transport.connect()
  File "/usr/local/lib/python3.6/site-packages/smbprotocol/transport.py", line 60, in connect
    self._sock.connect((self.server, self.port))
TimeoutError: [Errno 60] Operation timed out
```

**Comment by chopraaa** [comment]
I had this issue as well but I figured it was just my network.

**Comment by jborean93** [comment]
@hdansou yea this doesn't seem like an issue in the library but something with your network. The underlying socket timed out when creating the initial socket.

* Is it on the same network as the one where you tested with psexec?
* Did you change the IP address in the logs, if not the address seems to be unusual.

The first point can probably narrow it down as if they are not on the same network there's probably a firewall in the way.

**Comment by hdansou** [comment]
I have just discovered that my new ISP is blocking outbound connection on port 445.
I have set up a VPN and successfully tested pypsexec from macOS. 

On a side note, I had the IP address redacted in my previous comment.

**Comment by jborean93** [comment]
@hdansou no worries, glad it wasn't an issue with the library and you were able to resolve it.

**Comment by parkerduckworth** [comment]
Can confirm that this is still an issue on macOS Monterey (v12.5.1), and that using a VPN circumvents the problem.
